project:
  title: "abntexQuarto"

number-sections: true
bibliography: "references.bib"
csl: "src/abnt.csl"

link-citations: true

fig-cap-location: top

crossref:
  lof-title: "Lista de Figuras"
  lot-title: "Lista de Tabelas"
  lol-title: "Lista de Códigos"
  fig-title: "Figura"
  tbl-title: "Tabela"
  lst-title: "Código"
  fig-prefix: "Fig."
  tbl-prefix: "Tab."
  lst-prefix: "Cód."

format:
  pdf:
    include-in-header: "./src/preamble.tex"
    documentclass: "abntex2"
    classoption: 
      - 12pt
      - oneside
      - a4paper
      - english
      - brazil
    geometry:
      - top=30mm
      - left=30mm
      - right=20mm
      - bottom=20mm
    colorlinks: true
    code-block-bg: true
    code-block-border-left: true
    highlight-style: github
    keep-tex: true

# html:
  #   page-layout: full